(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> contains() takes at least 3 arguments (4 given)"
p3
sS'layer'
p4
S'/home/rogoberto/web2py/applications/aluminum/controllers/cobranca.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f61b824d9b0, file "/home/rogoberto/web2py/applications/aluminum/controllers/cobranca.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/rogoberto/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/rogoberto/web2py/applications/aluminum/controllers/cobranca.py", line 362, in <module>\n  File "/home/rogoberto/web2py/gluon/globals.py", line 421, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/rogoberto/web2py/gluon/tools.py", line 3862, in f\n    return action(*a, **b)\n  File "/home/rogoberto/web2py/applications/aluminum/controllers/cobranca.py", line 124, in lista_registros\n    rows = db((db.registro_cobranca.sub_venda==sub_venda.id)&(db.registro_cobranca.tipo==tipo)&(db.registro_cobranca.descricao.contains(request.args(2)))).select(orderby=db.registro_cobranca.data_inicio)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/objects.py", line 2277, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 758, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 673, in _select_wcols\n    query = self.expand(query, query_env=query_env)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 435, in _expand\n    rv = op(first, second, **optional_args)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/dialects/base.py", line 228, in _and\n    self.expand(second, query_env=query_env))\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/dialects/__init__.py", line 96, in expand\n    return self.adapter.expand(*args, **kwargs)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 437, in _expand\n    rv = op(first, **optional_args)\nTypeError: contains() takes at least 3 arguments (4 given)\n'
p11
s.